name: End-to-end tests
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create env file
        run: |
        touch .env
        echo NEXT_PUBLIC_GRAPHQL_API=${{ https://cms-new-eog9k.ondigitalocean.app/graphql }} >> .env
        echo NEXT_PUBLIC_CMS_URL=${{ https://cms-new-eog9k.ondigitalocean.app }} >> .env
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn turbo run start-frontend
          project: ./packages/frontend
          wait-on: http://localhost:3000/
