name: End-to-end tests
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn turbo run start-cms, yarn turbo run start-frontend
          wait-on: "http://localhost:1337, http://localhost:3000"
          wait-on-timeout: 120
